//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace VirtualClient.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualClient.Actions.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameters:
        ///
        ///        timespan:   1
        ///        -------------
        ///        duration: 30s
        ///        warm up time: 15s
        ///        cool down time: 0s
        ///        measuring latency
        ///        gathering IOPS at intervals of 1000ms
        ///        random seed: 0
        ///        path: &apos;diskspd.dat&apos;
        ///                think time: 0ms
        ///                burst size: 0
        ///                software cache disabled
        ///                hardware write cache disabled, writethrough on
        ///                performing mix test (read/write ratio: 70/30)
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Results_DiskSpd_Text {
            get {
                return ResourceManager.GetString("Results_DiskSpd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;
        ///    &lt;System&gt;
        ///        &lt;ComputerName&gt;QuickTest2&lt;/ComputerName&gt;
        ///        &lt;Tool&gt;
        ///            &lt;Version&gt;2.0.21a&lt;/Version&gt;
        ///            &lt;VersionDate&gt;2018/9/21&lt;/VersionDate&gt;
        ///        &lt;/Tool&gt;
        ///        &lt;RunTime&gt;2021/04/14 23:25:42 UTC&lt;/RunTime&gt;
        ///        &lt;ProcessorTopology&gt;
        ///            &lt;Group Group=&quot;0&quot; MaximumProcessors=&quot;4&quot; ActiveProcessors=&quot;4&quot; ActiveProcessorMask=&quot;0xf&quot;/&gt;
        ///            &lt;Node Node=&quot;0&quot; Group=&quot;0&quot; Processors=&quot;0xf&quot;/&gt;
        ///            &lt;Socket&gt;
        ///                &lt;Group Group=&quot;0&quot; Processors=&quot;0xf&quot;/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Results_DiskSpd_Xml {
            get {
                return ResourceManager.GetString("Results_DiskSpd_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fio: pid=8281, err=84/file:io_u.c:2141, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character.
        /// </summary>
        internal static string Results_FIO_Error_1 {
            get {
                return ResourceManager.GetString("Results_FIO_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fio: pid=4879, err=84/file:io_u.c:2141, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character 1
        ///fio: pid=4904, err=84/file:io_u.c:2141, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character 2
        ///fio: pid=4903, err=84/file:io_u.c:2141, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character 3
        ///fio: pid=4888, err=84/file:io_u.c:2141, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character 4
        ///.
        /// </summary>
        internal static string Results_FIO_Error_2 {
            get {
                return ResourceManager.GetString("Results_FIO_Error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;fio version&quot; : &quot;fio-3.26&quot;,
        ///  &quot;timestamp&quot; : 1618699271,
        ///  &quot;timestamp_ms&quot; : 1618699271417,
        ///  &quot;time&quot; : &quot;Sat Apr 17 22:41:11 2021&quot;,
        ///  &quot;jobs&quot; : [
        ///    {
        ///      &quot;jobname&quot; : &quot;fio_randrw_1GB_4k_d1_th1_direct&quot;,
        ///      &quot;groupid&quot; : 0,
        ///      &quot;error&quot; : 0,
        ///      &quot;eta&quot; : 0,
        ///      &quot;elapsed&quot; : 122,
        ///      &quot;job options&quot; : {
        ///        &quot;name&quot; : &quot;fio_randrw_1GB_4k_d1_th1_direct&quot;,
        ///        &quot;ioengine&quot; : &quot;libaio&quot;,
        ///        &quot;size&quot; : &quot;1GB&quot;,
        ///        &quot;numjobs&quot; : &quot;1&quot;,
        ///        &quot;rw&quot; : &quot;randwrite&quot;,
        ///        &quot;bs&quot; : &quot;4k&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Results_FIO_JSON {
            get {
                return ResourceManager.GetString("Results_FIO_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha256: verify failed at file fio_randwrite_1GB_32k_d1_th1_direct.0.0 offset 668565504, length 32768 (requested block: offset=668565504, length=32768, flags=88)
        ///       Expected CRC: d8f4f08bfc814742430981c12ff93a1628a18e73657e44128000000000000000000000000000000000000000000000000000000000000000c0fc030000000000
        ///       Received CRC: a900d077f2091480430981c12ff93a1628a18e73657e44128000000000000000000000000000000000000000000000000000000000000000c0fc030000000000
        ///.
        /// </summary>
        internal static string Results_FIO_Verification_Error_1 {
            get {
                return ResourceManager.GetString("Results_FIO_Verification_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fio_randrw_1GB_4k_d1_th1_direct: (g=0): rw=randrw, bs=(R) 64.0KiB-64.0KiB, (W) 64.0KiB-64.0KiB, (T) 64.0KiB-64.0KiB, ioengine=libaio, iodepth=16
        ///...
        ///fio-3.26-19-ge7e53
        ///Starting 32 threads
        ///fio_randrw_1GB_4k_d1_th1_direct: Laying out IO file (1 file / 250MiB)
        ///verify: bad header numberio 3932, wanted 0 at file /home/azureuser/VirtualClient.1.0.1673.1/content/linux-x64/remote_disk_1_1/xejahjpg.cjd offset 229900288, length 65536 (requested block: offset=229900288, length=65536)
        ///verify: bad header numberio 3835,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Results_FIO_Verification_Error_2 {
            get {
                return ResourceManager.GetString("Results_FIO_Verification_Error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version: 3.0.0-beta3-dev
        ///built on: built on: Thu Aug  5 18:45:56 2021 UTC
        ///options:bn(64,64) 
        ///compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
        ///CPUINFO: OPENSSL_ia32cap=0xfeda32235f8bffff:0x405f46f1bf2fb9
        ///The &apos;numbers&apos; are in 1000s of bytes per second processed.
        ///type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
        ///AES-256-CBC    1109022.36k  1209391.13k  1232451.87k  12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Results_OpenSSL_speed {
            get {
                return ResourceManager.GetString("Results_OpenSSL_speed", resourceCulture);
            }
        }
    }
}
