//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;hello&quot;: &quot;world&quot;
        ///}.
        /// </summary>
        internal static string Response1 {
            get {
                return ResourceManager.GetString("Response1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;fio version&quot; : &quot;fio-3.26&quot;,
        ///  &quot;timestamp&quot; : 1618699271,
        ///  &quot;timestamp_ms&quot; : 1618699271417,
        ///  &quot;time&quot; : &quot;Sat Apr 17 22:41:11 2021&quot;,
        ///  &quot;jobs&quot; : [
        ///    {
        ///      &quot;jobname&quot; : &quot;fio_randwrite_1GB_4k_d1_th1_direct&quot;,
        ///      &quot;groupid&quot; : 0,
        ///      &quot;error&quot; : 0,
        ///      &quot;eta&quot; : 0,
        ///      &quot;elapsed&quot; : 122,
        ///      &quot;job options&quot; : {
        ///        &quot;name&quot; : &quot;fio_randwrite_1GB_4k_d1_th1_direct&quot;,
        ///        &quot;ioengine&quot; : &quot;windowsaio&quot;,
        ///        &quot;size&quot; : &quot;1GB&quot;,
        ///        &quot;numjobs&quot; : &quot;1&quot;,
        ///        &quot;rw&quot; : &quot;randwrite&quot;,
        ///        &quot;bs&quot; :  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response2 {
            get {
                return ResourceManager.GetString("Response2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;fio version&quot; : &quot;fio-3.26-19-ge7e53&quot;,
        ///  &quot;timestamp&quot; : 1646873555,
        ///  &quot;timestamp_ms&quot; : 1646873555274,
        ///  &quot;time&quot; : &quot;Thu Mar 10 00:52:35 2022&quot;,
        ///  &quot;jobs&quot; : [
        ///    {
        ///      &quot;jobname&quot; : &quot;disk_fill&quot;,
        ///      &quot;groupid&quot; : 0,
        ///      &quot;error&quot; : 0,
        ///      &quot;eta&quot; : 0,
        ///      &quot;elapsed&quot; : 6,
        ///      &quot;job options&quot; : {
        ///        &quot;name&quot; : &quot;disk_fill&quot;,
        ///        &quot;size&quot; : &quot;1GB&quot;,
        ///        &quot;numjobs&quot; : &quot;1&quot;,
        ///        &quot;rw&quot; : &quot;readwrite&quot;,
        ///        &quot;bs&quot; : &quot;256k&quot;,
        ///        &quot;iodepth&quot; : &quot;64&quot;,
        ///        &quot;direct&quot; : &quot;1&quot;,
        ///        &quot;overwrit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response3 {
            get {
                return ResourceManager.GetString("Response3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;example&quot;: &quot;virtual client&quot;,
        ///    &quot;workload&quot;: 1
        ///}.
        /// </summary>
        internal static string Response4 {
            get {
                return ResourceManager.GetString("Response4", resourceCulture);
            }
        }
    }
}
