//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;!-- generated by lshw-B.02.18 --&gt;
        ///&lt;!-- GCC 7.5.0 --&gt;
        ///&lt;!-- Linux 5.4.0-1046-azure #48~18.04.1-Ubuntu SMP Tue Apr 13 19:41:38 UTC 2021 x86_64 --&gt;
        ///&lt;!-- GNU libc 2 (glibc 2.27) --&gt;
        ///&lt;list&gt;
        ///    &lt;node id=&quot;disk:0&quot; claimed=&quot;true&quot; class=&quot;disk&quot; handle=&quot;GUID:8baf2489-b867-4532-bf70-b34611d9cd15&quot;&gt;
        ///        &lt;description&gt;SCSI Disk&lt;/description&gt;
        ///        &lt;product&gt;Virtual Disk&lt;/product&gt;
        ///        &lt;vendor&gt;Msft&lt;/vendor&gt;
        ///        &lt;physid&gt;0.0.0&lt;/physid&gt;
        ///        &lt;businfo&gt;scsi@0:0.0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lshw_disk_storage_results {
            get {
                return ResourceManager.GetString("lshw_disk_storage_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;!-- generated by lshw-B.02.18 --&gt;
        ///&lt;!-- GCC 7.5.0 --&gt;
        ///&lt;!-- Linux 5.4.0-1046-azure #48~18.04.1-Ubuntu SMP Tue Apr 13 19:41:38 UTC 2021 x86_64 --&gt;
        ///&lt;!-- GNU libc 2 (glibc 2.27) --&gt;
        ///&lt;list&gt;
        ///    &lt;node id=&quot;disk:0&quot; claimed=&quot;true&quot; class=&quot;disk&quot; handle=&quot;GUID:8baf2489-b867-4532-bf70-b34611d9cd15&quot;&gt;
        ///        &lt;description&gt;SCSI Disk&lt;/description&gt;
        ///        &lt;product&gt;Virtual Disk&lt;/product&gt;
        ///        &lt;vendor&gt;Msft&lt;/vendor&gt;
        ///        &lt;physid&gt;0.0.0&lt;/physid&gt;
        ///        &lt;businfo&gt;scsi@0:0.0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lshw_disk_storage_results_before_partitioning {
            get {
                return ResourceManager.GetString("lshw_disk_storage_results_before_partitioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;!-- generated by lshw-B.02.18 --&gt;
        ///&lt;!-- GCC 7.5.0 --&gt;
        ///&lt;!-- Linux 5.4.0-1046-azure #48~18.04.1-Ubuntu SMP Tue Apr 13 19:41:38 UTC 2021 x86_64 --&gt;
        ///&lt;!-- GNU libc 2 (glibc 2.27) --&gt;
        ///&lt;list&gt;
        ///    &lt;node id=&quot;disk:0&quot; claimed=&quot;true&quot; class=&quot;disk&quot; handle=&quot;GUID:8baf2489-b867-4532-bf70-b34611d9cd15&quot;&gt;
        ///        &lt;description&gt;SCSI Disk&lt;/description&gt;
        ///        &lt;product&gt;Virtual Disk&lt;/product&gt;
        ///        &lt;vendor&gt;Msft&lt;/vendor&gt;
        ///        &lt;physid&gt;0.0.0&lt;/physid&gt;
        ///        &lt;businfo&gt;scsi@0:0.0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lshw_disk_storage_results_with_cdrom {
            get {
                return ResourceManager.GetString("lshw_disk_storage_results_with_cdrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;!-- generated by lshw-B.02.18 --&gt;
        ///&lt;!-- GCC 7.5.0 --&gt;
        ///&lt;!-- Linux 5.4.0-1046-azure #48~18.04.1-Ubuntu SMP Tue Apr 13 19:41:38 UTC 2021 x86_64 --&gt;
        ///&lt;!-- GNU libc 2 (glibc 2.27) --&gt;
        ///&lt;list&gt;
        ///    &lt;node id=&quot;disk:0&quot; claimed=&quot;true&quot; class=&quot;disk&quot; handle=&quot;GUID:8baf2489-b867-4532-bf70-b34611d9cd15&quot;&gt;
        ///        &lt;description&gt;SCSI Disk&lt;/description&gt;
        ///        &lt;product&gt;Virtual Disk&lt;/product&gt;
        ///        &lt;vendor&gt;Msft&lt;/vendor&gt;
        ///        &lt;physid&gt;0.0.0&lt;/physid&gt;
        ///        &lt;businfo&gt;scsi@0:0.0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lshw_disk_storage_results_with_duplicate_index_and_logicalunit {
            get {
                return ResourceManager.GetString("lshw_disk_storage_results_with_duplicate_index_and_logicalunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;!-- generated by lshw-B.02.18 --&gt;
        ///&lt;!-- GCC 7.5.0 --&gt;
        ///&lt;!-- Linux 5.4.0-1051-azure #53~18.04.1-Ubuntu SMP Fri Jun 18 22:32:58 UTC 2021 x86_64 --&gt;
        ///&lt;!-- GNU libc 2 (glibc 2.27) --&gt;
        ///&lt;list&gt;
        ///  &lt;node id=&quot;namespace&quot; claimed=&quot;true&quot; class=&quot;disk&quot; handle=&quot;&quot;&gt;
        ///   &lt;description&gt;NVMe namespace&lt;/description&gt;
        ///   &lt;physid&gt;1&lt;/physid&gt;
        ///   &lt;logicalname&gt;/dev/nvme0n1&lt;/logicalname&gt;
        ///   &lt;size units=&quot;bytes&quot;&gt;960197124096&lt;/size&gt;
        ///   &lt;configuration&gt;
        ///    &lt;setting id=&quot;logicalsectorsize&quot; value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lshw_disk_storage_results_with_nvme {
            get {
                return ResourceManager.GetString("lshw_disk_storage_results_with_nvme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;!-- generated by lshw-B.02.18 --&gt;
        ///&lt;!-- GCC 7.5.0 --&gt;
        ///&lt;!-- Linux 5.13.1-0-ref-generic #0 SMP Wed Jul 28 13:20:59 UTC 2021 aarch64 --&gt;
        ///&lt;!-- GNU libc 2 (glibc 2.27) --&gt;
        ///&lt;list&gt;
        ///    &lt;node id=&quot;disk&quot; claimed=&quot;true&quot; class=&quot;disk&quot; handle=&quot;SCSI:00:00:00:00&quot;&gt;
        ///        &lt;description&gt;
        ///            SCSI Disk
        ///        &lt;/description&gt;
        ///        &lt;product&gt;
        ///            Virtual Disk
        ///        &lt;/product&gt;
        ///        &lt;vendor&gt;
        ///            Msft
        ///        &lt;/vendor&gt;
        ///        &lt;physid&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lshw_disk_storage_results_with_volume_without_logicalname {
            get {
                return ResourceManager.GetString("lshw_disk_storage_results_with_volume_without_logicalname", resourceCulture);
            }
        }
    }
}
