<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <RunCodeAnalysis>false</RunCodeAnalysis>
        <RunAnalyzers>false</RunAnalyzers>
        <RootNamespace>VirtualClient.Actions</RootNamespace>
        <NoWarn>AsyncFixer02;SA1005;SA1120</NoWarn>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Moq" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" />
	</ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VirtualClient.Actions\VirtualClient.Actions.csproj" />
        <ProjectReference Include="..\VirtualClient.Contracts\VirtualClient.Contracts.csproj" />
        <ProjectReference Include="..\VirtualClient.TestExtensions\VirtualClient.TestExtensions.csproj" />
    </ItemGroup>

    <ItemGroup>
       
    </ItemGroup>

	<ItemGroup>
		<None Include="..\TestResources\**\*">
			<Link>TestResources\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</None>

		<None Update="SPEC\mockspeccpu.cfg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<!--
    Copies example resources into the target output directory.
    -->
	<Target Name="CopyExamplesToOutputDirectory" AfterTargets="Build">
		<ItemGroup>
			<TestExampleFiles Include="Examples\**\*.*" />
		</ItemGroup>

		<Copy SourceFiles="@(TestExampleFiles)" DestinationFiles="@(TestExampleFiles->'$(OutputPath)test_examples\%(RecursiveDir)%(Filename)%(Extension)')" />
	</Target>

	<!--
    Copies test resources into the target output directory.
    -->
	<Target Name="CopyTestResourcesToOutputDirectory" AfterTargets="CopyExamplesToOutputDirectory">
		<ItemGroup>
			<TestResourceFiles Include="..\TestResources\**\*.*" />
		</ItemGroup>

		<Copy SourceFiles="@(TestResourceFiles)" DestinationFiles="@(TestResourceFiles->'$(OutputPath)test_resources\%(RecursiveDir)%(Filename)%(Extension)')" />
	</Target>

    <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), Module.props))\Module.props" />

</Project>
