# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the OneBranch template
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - website
pr: none

variables:
- name: VcVersion
  value: 1.14.1
- name: ROOT
  value: $(Build.SourcesDirectory)
- name: CDP_DEFINITION_BUILD_COUNT
  value: $[counter('', 0)]
- name: ENABLE_PRS_DELAYSIGN
  value: 1
- name: WindowsContainerImage
  value: onebranch.azurecr.io/windows/ltsc2019/vse2022:latest

resources:
  repositories:
  - repository: onebranchTemplates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
    
extends:
  template: v2/OneBranch.Official.CrossPlat.yml@onebranchTemplates
  parameters:
    customTags: 'ES365AIMigrationTooling-BulkMigrated'
    stages:
    - stage: stage
      jobs:
      - job: job
        pool:
          type: windows
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
        steps:
        - task: UseDotNet@2
          continueOnError: false
          inputs:
            packageType: 'sdk'
            version: '2.1.x'
        - task: UseDotNet@2
          continueOnError: false
          inputs:
            packageType: 'sdk'
            version: '8.0.101'
            useGlobalJson: false
            performMultiLevelLookup: true
            workingDirectory: '$(Build.SourcesDirectory)'
        - script: $(Build.SourcesDirectory)\clean.cmd
          displayName: 'Clean Output Directories'
        - script: $(Build.SourcesDirectory)\build.cmd $(VcVersion)
          displayName: 'Build Solutions'
        - script: $(Build.SourcesDirectory)\build-packages.cmd $(VcVersion)$(VersionSuffix)
          displayName: 'Build NuGet Packages'
        - task: EsrpCodeSigning@1
          inputs:
            ConnectedServiceName: 'virtualclient-esrp'
            FolderPath: '$(System.DefaultWorkingDirectory)'
            Pattern: '*.nupkg'
            signConfigType: 'inlineSignParams'
            inlineOperation: |
              [    
                  {
                    "KeyCode": "CP-401405",
                    "OperationCode": "NuGetSign",
                    "Parameters": {},
                    "ToolName": "sign",
                    "ToolVersion": "1.0"
                  },
                  {
                    "KeyCode": "CP-401405",
                    "OperationCode": "NuGetVerify",
                    "Parameters": {},
                    "ToolName": "sign",
                    "ToolVersion": "1.0"
                  }
              ]
            SessionTimeout: '60'
            MaxConcurrency: '50'
            MaxRetryAttempts: '5'
        - script: $(Build.SourcesDirectory)\upload-packages.cmd $(Build.SourcesDirectory)\out\packages $(NUGETORGAPIKEY)
          displayName: 'Publish NuGet Packages'