name: PR Build check for Docusaurus site

on:
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    working-directory: ./website

jobs:
  deploy:
    name: Document Website Build Check
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build website
        run: yarn build
